apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "pytorch-dist-mnist-gloo"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: quay.io/mcampbel/fms-hf-tuning:pytorch-hip4
              args: ["--backend", "gloo"]
              env:
                - name: "HSA_OVERRIDE_GFX_VERSION"
                  value: gfx1100
              # Comment out the below resources to use the CPU.
              resources:
                limits:
                  "amd.com/gpu": "1"
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: quay.io/mcampbel/fms-hf-tuning:pytorch-hip4
              args: ["--backend", "gloo"]
              env:
                - name: "HSA_OVERRIDE_GFX_VERSION"
                  value: gfx1100
#               Comment out the below resources to use the CPU.
              resources:
                limits:
                  "amd.com/gpu": "1"

